[package]
name = "trying_image"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_egui = "0.27.0"
image = "0.25.1"
egui_extras = { version = "0.27.0", features = ["all_loaders"] }