[package]
name = "SurrealTesting"
version = "0.1.0"
edition = "2021"

[dependencies]
surrealdb = { version = "1.0.0", features = ["kv-rocksdb"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bacon = "2.21.0"
